version: '3.8'
services:
  sonarqube:
    image: my-sonarqube-image
    container_name: sonarqube
    network_mode: host
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_LOG_LEVEL=INFO
      - SONAR_SCANNER_JAVA_OPTS=-Xmx512m
      - SONAR_JDBC_URL=jdbc:postgresql://127.0.0.1:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpassword

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
